# Configuration file for recon framework

wordlists:
  subdomain: "/usr/share/wordlists/all.txt"

paths:
  subfinder: "$(which subfinder)"
  naabu: "$(which naabu)"
  gowitness: "$(which gowitness)"
  waybackurls: "$(which waybackurls)"
